version: '3.8'

services:
  frontend-dev:
    command: bash
    image: node:latest
    ports:
      - "5173:5173"
    user: "501:501"
    volumes:
      - ./frontend:/app
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - dev.env



